### ISSUE TITLE
perform_all? 

### ISSUE THREAD

**Issue by chrishough** [gocardless/rspec-que#6]
When you are testing various jobs in Rspec is there something that can execute the jobs inside the queue similar to `ResqueSpec.perform_all(queue_name)`?   

Thoughts?

**References**
https://github.com/leshill/resque_spec
https://github.com/gocardless/rspec-que

**Comment by hmac** [comment]
@chrishough you can set `Que.mode = :sync` to make Que work jobs synchronously as they are enqueued. We use this a lot when testing jobs. The [Que README](https://github.com/chanks/que#usage) has more info.

**Comment by chrishough** [comment]
I completely forgot about this issue, and yes, that is the way we took it. Thank you.
